#include <stdio.h>
#include "fibCalc.h"
#include "fibonacciCalculation.h"
#include "fibonacciCalculation_initialize.h"
#include "fibonacciCalculation_terminate.h"

int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    /* Initialize the application. */
    fibonacciCalculation_initialize();

    if(argc < 2)
    {
        printf("Usage: %s <n>\n", argv[0]);
        return 1;
    }
    /* Call the autogenerated Fibonacci function */
    double result = fibonacciCalculation(atoi(argv[1]));

    /* Print the result */
    printf("Fibonacci(%d) = %.0f\n", atoi(argv[1]), result);

    /* Terminate the application */
    fibonacciCalculation_terminate();

    return result;
}