#include <stdio.h>
#include "fibCalc.h"
#include "fibonacciCalculation.h"
#include "fibonacciCalculation_initialize.h"
#include "fibonacciCalculation_terminate.h"

int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    /* Initialize the application. */
    fibonacciCalculation_initialize();

    /* Ask user for input */
    double n;
    printf("Enter a non-negative integer for Fibonacci calculation: ");
    scanf("%lf", &n);

    /* Call the autogenerated Fibonacci function */
    double result = fibonacciCalculation(n);

    /* Print the result */
    printf("Fibonacci(%.0f) = %.0f\n", n, result);

    /* Terminate the application */
    fibonacciCalculation_terminate();

    printf("\nBerechnung abgeschlossen. Druecken Sie eine Taste zum Beenden...\n");
    
    while (getchar() != '\n'); 
    
    // Wartet auf die nächste Eingabe (beliebige Taste)
    getchar();

    return 0;
}
